### ISSUE TITLE
CT: Assertion failed: Thermal energy should be non-negative

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park-basics#462] opened 2019-10-11 14:47 UTC
This has been occurring intermittently for a few days.

```
energy-skate-park-basics : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], oldPotentialEnergy:-0.0005937381116468495, skaterPositionY:-9.693683455458768e-7, initialEnergy: -0.0005937381116468495, proposedPosition: Vector2(-4.332890460897849, 0), proposedVelocity: Vector2(1.0000805158682254e-17, -0.16333333333333333), dt: 0.016666666666666666, newSpeed: 1.0000805158682254e-17, newKineticEnergy: 3.125503244435175e-33, newPotentialEnergy: 0, newThermalEnergy: -0.0005937381116468495, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], oldPotentialEnergy:-0.0005937381116468495, skaterPositionY:-9.693683455458768e-7, initialEnergy: -0.0005937381116468495, proposedPosition: Vector2(-4.332890460897849, 0), proposedVelocity: Vector2(1.0000805158682254e-17, -0.16333333333333333), dt: 0.016666666666666666, newSpeed: 1.0000805158682254e-17, newKineticEnergy: 3.125503244435175e-33, newPotentialEnergy: 0, newThermalEnergy: -0.0005937381116468495, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/assert/js/assert.js?bust=1570801832778:22:13)
    at PlaygroundModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1570801832865:539:17)
    at PlaygroundModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1570801832865:576:21)
    at PlaygroundModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1570801832865:1038:21)
    at PlaygroundModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1570801832865:1348:39)
    at PlaygroundModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1570801832865:416:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/joist/js/Sim.js?bust=1570801832865:217:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/axon/js/Action.js?bust=1570801832865:238:20)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/joist/js/Sim.js?bust=1570801832865:958:33)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1570777834985/joist/js/Sim.js?bust=1570801832865:939:14)
id: Bayes Chrome
Approximately 10/11/2019, 1:10:34 AM
```

**Comment by jessegreenberg** [comment] 2019-12-18 22:31
A fix for this was proposed and committed in https://github.com/phetsims/energy-skate-park/issues/45, the issue is being tracked there.

**Closed by jessegreenberg** 2019-12-18 22:31 UTC
Labels: type:automated-testing
