### ISSUE TITLE
Track nodes snap together but do not connect

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/energy-skate-park-basics#384] opened 2017-09-27 21:43 UTC
Found while testing phetsims/QA#50
Steps to reproduce:
On the playground screen, drag out two pieces of track just a little (not above ground level). They will snap to ground level, and overlap each other. Grab one of them by the center node, and lift it up, then grab the other track by its center node and lift it up. The one endpoint of the second track will snap to overlap the endpoint of the first track, but they will not connect until you click or move one of those endpoints. 
Also, sometimes moving the tracks will cause gray artifacts to appear as you can see in the gif.
![r1](https://user-images.githubusercontent.com/11947677/30989017-7b0960a2-a459-11e7-8cbb-c747d072cfbd.gif)

This problem does not appear to be specific to platform or sim version. Found initially on 1.4.0-phetiorc.1, but it occurs on the live version on the phet website, and I looked at 1.3.1-dev.6 as well since it was the most recent non io version.

**Comment by brroberts1231** [comment] 2017-09-27 21:47
(Erroneously hit enter after I typed title, ignore this until I actually type the whole thing)

**Comment by samreid** [comment] 2017-11-13 01:49
I can't reproduce this in master, but it is likely because the tracks are no longer popping above ground level--this is likely a new bug.

**Comment by samreid** [comment] 2017-11-14 17:34
The simplest solution to this problem will create a change in behavior--previously (and in the published version) if you click on a track in the toolbox and release nothing happens.  For the proposed fix, if you tap a track in the toolbox and release, it will pop above the track.  I suspect it will be fine, but would be good to run it past the design team before publishing this change.  @ariel-phet can you comment?

**Comment by samreid** [comment] 2017-11-14 17:35
Fix for https://github.com/phetsims/energy-skate-park-basics/issues/384#issuecomment-343788762 committed above and available for testing on phettest.

**Comment by samreid** [comment] 2017-11-14 17:38
Also after fixing https://github.com/phetsims/energy-skate-park-basics/issues/384#issuecomment-343788762 I can now easily see the behavior described in https://github.com/phetsims/energy-skate-park-basics/issues/384#issue-261127691.  @ariel-phet can you please reproduce that problem and let me know what you recommend for the desired behavior?

**Comment by samreid** [comment] 2017-11-14 17:52
@brroberts1231 can you please indicate which browser(s) show the gray artifacts?  I haven't been able to see them on Mac/Chrome or Mac/Firefox.

@ariel-phet said the rest of the behavior aside from the gray artifacts is ok, so we'll investigate the gray artifacts a bit more before closing.

**Comment by samreid** [comment] 2017-12-22 20:36
Testing the requirejs version, I still do not see the gray artifacts on Mac Chrome.  Win10 Chrome and Win10 Edge also show no gray artifacts.  @ariel-phet do you want more testing on this before next Dev test?

**Comment by ariel-phet** [comment] 2017-12-28 19:12
@samreid, no lets go ahead and close for the moment

**Comment by jessegreenberg** [comment] 2018-05-30 17:23
From #205 we may need a different fix for this. @samreid said

>  if you tap the track in the toolbox 5 times, you will deplete the track from the toolbox--that seems odd.

This commit reintroduced #205:
https://github.com/phetsims/energy-skate-park-basics/commit/7b7b1783686a3e17efe93b08db3df3970f075ed1

**Comment by jessegreenberg** [comment] 2018-05-30 17:27
Reading this issue more, I see that https://github.com/phetsims/energy-skate-park-basics/commit/7b7b1783686a3e17efe93b08db3df3970f075ed1 was a fix for a bug where tracks were no longer popping above ground.

But in https://github.com/phetsims/energy-skate-park-basics/issues/384#issuecomment-344341800 @ariel-phet said that the behavior in the original issue ticket was OK.

**Comment by jessegreenberg** [comment] 2018-05-30 17:37
https://github.com/phetsims/energy-skate-park-basics/commit/7b7b1783686a3e17efe93b08db3df3970f075ed1 added

```js
      track.bumpAboveGround();
```
to trackDragEnded.

I was recently browsing old versions of this code and could have sworn that line used to be further down in the `trackDragEnded` listener. Ill look around.

**Comment by jessegreenberg** [comment] 2018-05-30 17:40
It was in daebed6. This will be fixed if 
```js
this.bumpAboveGround;
```
gets moved into `if ( this.startedDrag )` check.

But why was it removed?

**Comment by jessegreenberg** [comment] 2018-05-30 17:54
Fixed in the above commit, the track is bumped above ground only if the track hasn't been disposed and only if drag has started. This issue can be closed again.

**Closed by jessegreenberg** 2018-05-30 17:54 UTC
Labels: type:bug
