### ISSUE TITLE
Teleporting and Falling Skater

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park-basics#127] opened 2014-04-24 19:27 UTC
It's possible to manipulate the track in a way to have the skater fall through, or possibly teleport to the end. The simple version of reproducing this is to go to the playground screen after opening the sim and take a single track. Shape this track into a mountain, or upside down "U". Place the skater directly on top of the middle node (or as close as you can, the closer the better) and quickly! after the skater is placed drag the middle node upward, even just a little, and the skater should either fall through or appear at the end of the track. Note in these screenshots how the total energy changes after the teleport:
![normal energy](https://cloud.githubusercontent.com/assets/5863899/2793687/42f0e368-cbe3-11e3-9460-25b5124ce35e.png)

After the teleport:
![teleportation energy](https://cloud.githubusercontent.com/assets/5863899/2793723/bc6116b4-cbe3-11e3-81de-86e6419797f3.png)

The second screenshot was hard to capture directly after the teleport, so the bar chart shows the results of falling off and hitting the ground as well. As a side note, the teleportation happened consistently for me when the skater was slightly moving towards the left end before moving the middle node, while the skater just fell through every time instead when she was falling slightly to the right.

This issue still occurs when additional tracks are attached, but the actual reproduction gets complicated. Present in 1.0.0-dev.48 on Windows 8.1( IE11, Chrome 34, Firefox 28), iPad2 & 3 (7.1/Safari 9537.53), and Chromebook (Chrome 34, Snow.2695.117.0)

**Comment by phet-steele** [comment] 2017-09-25 19:18
@samreid this came up again in phetsims/QA/issues/50 and can be reproduced the same way as originally reported in this issue. The newly reported issue is #383, which turns out to be a variant where this procedure is performed along the ground (thanks @BryceAG). There is also a chance (not 100%) that the ground variant will give the error reported in #367.

**Comment by phet-steele** [comment] 2017-09-25 19:18
Also, this is present in production.

**Comment by samreid** [comment] 2017-11-13 01:53
I'm seeing a problem where putting the skater at exactly the right location on the hill causes a teleport and total energy change.  Off by 1 pixel in either direction and the problem does not occur.

**Comment by samreid** [comment] 2017-11-13 14:31
It seems I am unable to reproduce the problem if putting the `numDivisions` to 1 instead of 4.

**Comment by samreid** [comment] 2017-11-13 18:53
With the query parameter `?debugLog` and reproducing the error, I see:

```
Changed position, wanted to change velocity, but didn't have enough to fix it..., dE=...
```

The code from that context is:

```js
              else {

                // TODO: This error case can still occur, especially with friction turned on
                debug && debug( 'Changed position, wanted to change velocity, but didn\'t have enough to fix it..., dE=' + ( newState.getTotalEnergy() - e0 ) );
              }
            }
            return correctedState;
```

So it is still returning the attempted correction even though it wasn't able to fully correct for the detected energy discrepancy.  I tried changing this to:

```js
              else {

                // TODO: This error case can still occur, especially with friction turned on
                debug && debug( 'Changed position, wanted to change velocity, but didn\'t have enough to fix it..., dE=' + ( newState.getTotalEnergy() - e0 ) );

                // TODO: what about running the model for a step with friction off?
                return newState;
              }
```

And the buggy behavior went away--there may still be numerical errors in the energy but they weren't apparent at the scale of the bar chart for this problem.

Another idea would be to return `oldState` instead of `newState`.  This would guarantee there are no energy problems but the skater motion would pause when in this error case.

I also noticed the code comment that suggests the problem is correlated to friction--when we detect this corner case, we could try temporarily disabling friction (for one frame), then updating the model with no friction, then re-enabling friction to see if it can get past the problematic spot.

@ariel-phet will you please review my notes and recommend which strategy to investigate?

**Comment by ariel-phet** [comment] 2017-11-14 00:34
@samreid it seems what you are proposing is a bit "hacky"

Since this sim is instrumented for PhET-iO can't we read out the state that is occurring in this circumstance? It seems like the model and the sim should be able to handle what is going on. My guess is you are putting the skater at an unstable equilibrium point and a small numerical fluctuation is getting it to move. It would be good to know exactly what the sim/model is doing in this case and try to fix the root issue.

**Comment by samreid** [comment] 2017-11-14 00:50
Yes, all the proposals from my comment were workarounds to address this case in isolation without disrupting the rest of the behavior.  I'll take a closer look to try to understand the root cause.

**Comment by samreid** [comment] 2017-11-14 03:14
I added this test scaffolding after the energy correction:

```js
        // Correct energy
        var correctedState = this.correctEnergy( skaterState, newState );

        if ( correctedState === null ) {
          newState = skaterState;
          for ( var i = 0; i < numDivisions; i++ ) {
            newState = this.stepEuler( dt / numDivisions, newState );
          }
          var z = this.correctEnergy( skaterState, newState );
        }
```

It helped me identify a flaw in the track search that was going to the edge of the track (and hence the teleport).  

After fixing this, there was still an energy discontinuity coming from the friction term.  The dynamics integration is not energy-conserving and the contribution from friction is increasing thermal energy too much.  When we tried an energy-conserving integration following http://digitalcommons.calpoly.edu/cgi/viewcontent.cgi?article=1387&context=phy_fac we ran into many complications so resorted to the strategy from the Java version.  For this corner case, I found that correcting the energy partly through the thermal overestimate and partly through the velocity overestimate it seems to (a) provide continuous motion without the skater getting stuck and (b) conserved energy.  I'll commit these changes and they will need some QA testing.

**Comment by samreid** [comment] 2017-11-14 03:16
@phet-steele can you please test the preceding commit on phettest?

**Comment by phet-steele** [comment] 2017-11-30 22:12
I can't make this happen anymore....woohoo!

**Comment by samreid** [comment] 2017-12-02 13:32
Thanks, let's close this issue and the fix will go out with the next version.

**Closed by samreid** 2017-12-02 13:32 UTC
Labels: type:bug
