### ISSUE TITLE
"Assertion failed: Impossible set state" because of Nodes

### ISSUE THREAD

**Issue by zepumph** [phetsims/energy-skate-park-basics#395] opened 2017-11-09 21:37 UTC
Just like in https://github.com/phetsims/charges-and-fields/issues/142, this problem is happening here in the state wrapper when you click on a control point with the UI buttons that pop up. \

```
Assertion failed: Impossible set state:
energySkateParkBasics.playgroundScreen.view.trackNode_5.controlPointNode_2.controlPointUI
```

@samreid could you apply the same strategy for this?

**Comment by samreid** [comment] 2017-11-11 17:31
The problem is that this logic is used to create ControlPointUI in the source frame:

```js
        if ( dragEvents <= 3 && trackNode.parents.length > 0 ) {
```

That logic never gets called in the downstream sim and hence the control point UI isn't created there.  We need a more model-driven approach or a way to clearChildInstances and create these from scratch.  But maybe these control points are "transient" and not necessary for the state?  It is a question for https://github.com/phetsims/phet-io/issues/1238

**Comment by samreid** [comment] 2017-11-11 17:44
I got partway through implementing this only to discover that the downstream ControlPointNode has a TrackNode with no parents, so the reconstituted control point UI is not showing up.

**Comment by samreid** [comment] 2017-11-11 17:48
I could use @zepumph's help on this.

**Comment by zepumph** [comment] 2017-11-16 20:31
Marked as meeting. Unassigning until we get to it in the meeting.

**Comment by samreid** [comment] 2017-11-24 03:54
I solved this in a related issue by removing the control node UI buttons from the state, closing.

**Closed by samreid** 2017-11-24 03:54 UTC
Labels: dev:phet-io, meeting:phet-io, status:on-hold
