### ISSUE TITLE
Different automated test failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/energy-skate-park-basics#331] opened 2015-10-27 20:38 UTC
```
Error: Cannot normalize a zero-magnitude vector
    at r.normalized (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:542:21162)
    at i.n.nudge (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:544:12440)
    at i.n.stepTrack (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:544:11900)
    at i.n.stepModel (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:544:15583)
    at i.n.step (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:544:6001)
    at e.i.stepSimulation (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:569:10153)
    at e.i.runAnimationLoop (http://localhost/energy-skate-park-basics/build/energy-skate-park-basics_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:569:9664)
```

**Comment by phet-steele** [comment] 2016-10-11 16:31
@samreid it's almost been a year, and this error finally appeared in automated testing! (10/11/2016 10:00 AM). Here's a better stack trace 😄 .

```
Error: Cannot normalize a zero-magnitude vector
    at Vector2.normalized (http://phettest.colorado.edu/dot/js/Vector2.js?bust=1476202787169:256:15)
    at EnergySkateParkBasicsModel.nudge (http://phettest.colorado.edu/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1476202787169:917:38)
    at EnergySkateParkBasicsModel.stepTrack (http://phettest.colorado.edu/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1476202787169:898:36)
    at EnergySkateParkBasicsModel.stepModel (http://phettest.colorado.edu/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1476202787169:1106:39)
    at EnergySkateParkBasicsModel.step (http://phettest.colorado.edu/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1476202787169:377:31)
    at EnergySkateParkBasicsSim.stepSimulation (http://phettest.colorado.edu/joist/js/Sim.js?bust=1476202787169:733:26)
    at EnergySkateParkBasicsSim.runAnimationLoop (http://phettest.colorado.edu/joist/js/Sim.js?bust=1476202787169:669:12)
```

**Comment by jonathanolson** [comment] 2017-01-05 21:29
Another reproduction:

```
Error: Cannot normalize a zero-magnitude vector
    at Vector2.normalized (http://localhost:8080/e/snapshot-1483643331593/dot/js/Vector2.js?bust=1483643663410:256:15)
    at EnergySkateParkBasicsModel.nudge (http://localhost:8080/e/snapshot-1483643331593/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1483643663410:944:38)
    at EnergySkateParkBasicsModel.stepTrack (http://localhost:8080/e/snapshot-1483643331593/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1483643663410:884:27)
    at EnergySkateParkBasicsModel.stepModel (http://localhost:8080/e/snapshot-1483643331593/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1483643663410:1133:39)
    at EnergySkateParkBasicsModel.step (http://localhost:8080/e/snapshot-1483643331593/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1483643663410:404:31)
    at EnergySkateParkBasicsSim.stepSimulation (http://localhost:8080/e/snapshot-1483643331593/joist/js/Sim.js?bust=1483643663410:752:26)
    at EnergySkateParkBasicsSim.runAnimationLoop (http://localhost:8080/e/snapshot-1483643331593/joist/js/Sim.js?bust=1483643663410:690:12)
```

**Comment by phet-steele** [comment] 2017-01-17 22:12
@samreid, easily reproducible in the production sim:

1. Take a two node track and put both nodes directly over each other.
2. Place the skater on the tiny available area of the track:

![espb02](https://cloud.githubusercontent.com/assets/5863899/22042194/5c7d30d2-dcc7-11e6-9126-233d87cb296b.gif)

**Comment by samreid** [comment] 2017-02-02 21:07
I was able to reproduce this problem.

**Comment by samreid** [comment] 2017-02-10 03:59
I was able to reproduce the problem 7 days ago, but couldn't reproduce it in master.  Still, I guarded against the zero vector division in the above commit.

**Comment by samreid** [comment] 2017-02-10 04:01
Ready for testing here: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.4/energy-skate-park-basics_en.html

**Comment by phet-steele** [comment] 2017-02-17 17:23
@samreid I can no longer reproduce the problem. Back to you.

**Comment by samreid** [comment] 2017-02-17 18:21
Thanks @phet-steele, closing.

**Closed by samreid** 2017-02-17 18:21 UTC
Labels: type:automated-testing
