### ISSUE TITLE
Clicking the track box causes a new track to spawn in playground area

### ISSUE THREAD

**Issue by bryo5363** [phetsims/energy-skate-park-basics#205] opened 2014-08-28 19:27 UTC
Is this intentional? Sometimes the tracks can get a little mangled together when performing this operation.

**Comment by jessegreenberg** [comment] 2018-05-29 20:01
Reopening. While working on https://github.com/phetsims/energy-skate-park-basics/issues/413 I noticed that this issue has resurfaced in master. The issue is not present in the published version.

**Comment by jessegreenberg** [comment] 2018-05-29 20:29
Looks like it  was introduced in https://github.com/phetsims/energy-skate-park-basics/commit/7b7b1783686a3e17efe93b08db3df3970f075ed1 for https://github.com/phetsims/energy-skate-park-basics/issues/384

**Comment by jessegreenberg** [comment] 2018-05-29 20:30
From https://github.com/phetsims/energy-skate-park-basics/issues/384#issuecomment-344336314
> For the proposed fix, if you tap a track in the toolbox and release, it will pop above the track.

**Comment by jessegreenberg** [comment] 2018-05-29 20:35
I assume that proposal  was accepted because #384 has been closed. But there are still  comments in the code that suggest the behavior should not be this way.

> // A new press has started, but the user has not moved the track yet, so do not create it yet.  See #205
...
>// Keep track of whether the user has started to drag the track.  Click events should not create tracks, only drag events.  See #205

@samreid @ariel-phet can you please comment? Is it OK that clicking on the toolbox immediately creates a track without drag now?

**Comment by jessegreenberg** [comment] 2018-05-29 21:30
I went ahead and removed some comments and logic that was added for this issue assuming that we are good to go in #384. @ariel-phet if this change is OK please close. Otherwise please reassign to me and Ill revert and work on a new fix for #384.

**Comment by samreid** [comment] 2018-05-30 00:10
> @samreid @ariel-phet can you please comment? Is it OK that clicking on the toolbox immediately creates a track without drag now?

Creating on press (not drag) is consistent with behavior in other PhET sims.

**Comment by samreid** [comment] 2018-05-30 09:54
After reviewing the issue, I think I need to backtrack on my preceding comment.  I forgot in this simulation dragging does not work like Circuit Construction Kit, where there is an immediate and visible change to the dragged component on press.  Instead, in energy-skate-park-basics, if you tap the track in the toolbox 5 times, you will deplete the track from the toolbox--that seems odd.  I'm also seeing a bug where if you tap (not drag) a track from the toolbox, then drag any of its control points, the track can no longer be dragged by the gray part.  I do not know if that bug was caused by these changes or is a new issue.

**Comment by jessegreenberg** [comment] 2018-05-30 17:04
Thanks @samreid, that makes sense. I reverted the commit.

>  I'm also seeing a bug where if you tap (not drag) a track from the toolbox, then drag any of its control points, the track can no longer be dragged by the gray part. I do not know if that bug was caused by these changes or is a new issue.

Reproduced, and it is still around after reverting. Ill make a new issue.

**Comment by jessegreenberg** [comment] 2018-05-30 17:55
Fixed in the above commit, the tracks don't get bumped above ground until after drag has started. Re-closing.

**Closed by jessegreenberg** 2018-05-30 17:55 UTC
Labels: type:question
