### ISSUE TITLE
Large Energy From Catching Skater

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#424] opened 2018-07-11 23:49 UTC
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome
**Problem description:**
Total and Thermal Energy can become very large by letting skater leave track then using track to catch her and launch her again.  For phetsims/QA/issues/134  Likely connected to phetsims/energy-skate-park-basics/issues/422 and phetsims/energy-skate-park-basics#32 and phetsims/energy-skate-park-basics#418
**Steps to reproduce:** 
1. Go to the Playground Screen
2. Use the tracks to create a short ramp you can easily move and that the skateboarder can easily fly off off.  Select the button that allows for sticking to the track
3. Set the ramp high up and to the left of the screen.
4. Start the skater down the ramp
5. When the skater leaves the edge of the ramp, move the track to catch her before she hits the ground.
6. Move the track back up and to the left before the skater leaves the track once more
7. Repeat as many times as you are able

**Screenshots:**
![skate park catch](https://user-images.githubusercontent.com/41024075/42604889-30c4d804-8532-11e8-9720-e469d6e6d54f.gif)
Due to issues with the video maker I was unable to do as many iterations as I would like

Troubleshooting information (do not edit):
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1536x741
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by EthanWJohnson** [comment] 2018-07-12 21:19
You're able to achieve a similar effect by changing the track geometry the skater is on while going over it. Instead of catching and, grab a track vertex as the skater is near it and alter its positioning, adding on to the thermal and total energy indefinitely. 

![image](https://user-images.githubusercontent.com/22551096/42659791-976d996a-85e6-11e8-9439-529adeadb537.png)

From what i'm seeing here, the total/thermal energy seems to be increasing mostly when the track moves with the skater on it, with the increase in potential/thermal energy coming from elevated positions and friction. Possibly less of a bug and more a consequence of how the thermal energy is handled/unintended behavior?

**Comment by jessegreenberg** [comment] 2018-07-13 20:23
@arouinfar @ariel-phet @samreid the report in  https://github.com/phetsims/energy-skate-park-basics/issues/424#issue-340443387 is physically accurate because this is just adding more energy to the system indefinitely, right?

To prevent bars from leaving the panel, should we add arrows like in CL:B?
![capture](https://user-images.githubusercontent.com/6396244/42711426-0a6bd22e-86a5-11e8-8074-3cbe580d6d86.PNG)

Or maybe there is another way to limit this somehow, like zeroing the velocity and thermal energy when dragging the track? Hmm, I don't like that very much, sounds too limiting.

**Comment by samreid** [comment] 2018-07-15 22:51
It does seem similar to #422--I'll wait to hear from @ariel-phet before working on this.

**Comment by arouinfar** [comment] 2018-07-17 23:01
@KatieWoe interesting find. I do not think the behavior in your screen capture is physically incorrect, though it certainly reveals a design flaw with the bar graph itself.

If I play with the sim in a window with a narrow aspect ratio, it's quite possible for the bars to go beyond the bounds of the panel, simply by dragging the skater to the top of the window. This looks messy to me, so I would be in favor of the CLB-like solution @jessegreenberg proposed.

![image](https://user-images.githubusercontent.com/8419308/42849720-bc8358b2-89e1-11e8-80f4-4e7109474bfc.png)  ![image](https://user-images.githubusercontent.com/8419308/42849774-f5eafff6-89e1-11e8-94bd-aae3a32d2ce4.png)

@jessegreenberg @samreid I also think that @EthanWJohnson's https://github.com/phetsims/energy-skate-park-basics/issues/424#issuecomment-404654163 sounds like #422 to me.

**Comment by jessegreenberg** [comment] 2018-07-19 02:29
Thanks @arouinfar. @ariel-phet is this an enhancement we should add in energy-skate-park, and defer for the upcomming LoL/PhET-iO release?

**Comment by ariel-phet** [comment] 2018-09-27 05:48
@jessegreenberg @arouinfar yes, I agree we should add the CL:B style "off chart" arrows. I have reproduced this behavior, and certainly it is not incorrect physics as your are "pumping" energy into the system (I did the vertex control point moving). So I think the off the chart indicator is a nice solution.

**Comment by jessegreenberg** [comment] 2019-12-19 21:52
Arrows to indicate energy beyond graph limis are in this sim now and they were necessary for energy-skate-park. Closing.

**Closed by jessegreenberg** 2019-12-19 21:52 UTC
Labels: dev:enhancement
