### ISSUE TITLE
Crashes on iPads

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/energy-skate-park-basics#343] opened 2016-03-21 16:13 UTC
Related to https://github.com/phetsims/tasks/issues/550
Test device: iPad 2 Tycho

Operating System: iOS 9.3 (13E5231a)

Browser: Safari 601.1

Problem description: The sim crashed in the Intro screen while the skater was in the SHO track. An error message appeared while the sim was starting, this message also appeared on iPad 2 w/ 8.4.1. 

Steps to reproduce: 

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/12610678/13925312/78156f02-ef4d-11e5-89bc-802cad005d70.png)

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-rc.1/energy-skate-park-basics_en.html
Version: 1.1.0-rc.1 2016-03-18 03:00:21 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E5231a Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"2dfd7daf","branch":"HEAD"},"babel":{"sha":"f15f8275","branch":"master"},"brand":{"sha":"ac9ccaa7","branch":"HEAD"},"chipper":{"sha":"662df961","branch":"HEAD"},"dot":{"sha":"da78031b","branch":"HEAD"},"energy-skate-park-basics":{"sha":"05144e76","branch":"HEAD"},"joist":{"sha":"09590795","branch":"HEAD"},"kite":{"sha":"10ca8bf2","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"380b1fb5","branch":"HEAD"},"scenery":{"sha":"3984862d","branch":"HEAD"},"scenery-phet":{"sha":"5d9dafb2","branch":"HEAD"},"sherpa":{"sha":"fc4c2c96","branch":"HEAD"},"sun":{"sha":"3a0cabef","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by samreid** [comment] 2016-03-21 16:15
@elisemorgan can you try to reproduce this problem with `?screens=1` ? This could help us identify whether it is a memory problem.  Also, can this crash be reproduced reliably (without the `?screens=1`)?

**Comment by elisemorgan** [comment] 2016-03-21 16:27
Unable to reproduce again easily and no issues with ?screens=1. I suspect that this has more to do with the iPad than the sim

**Comment by elisemorgan** [comment] 2016-03-28 01:06
@phet-steele Is your poor rating for iPad 2 w/iOS 9.3 related to this issue?

**Comment by phet-steele** [comment] 2016-03-28 15:42
@elisemorgan you bet. The sim crashing certainly isn't "good" performance.

**Comment by ariel-phet** [comment] 2016-03-28 21:02
might be relevant

http://money.cnn.com/2016/03/28/technology/iphone-safari-bug/index.html

**Comment by phet-steele** [comment] 2016-03-28 21:11
Ah, except it certainly was happening on 9.2.1, perhaps this title is misleading

**Comment by phet-steele** [comment] 2016-03-28 21:16
@ariel-phet @samreid I've honestly made a good attempt to figure out why this happens. I'm leaning towards a memory problem since the sim loads and runs well with `?screens=1`. I've spent probably too much time trying to figure out how to find memory leaks with Xcode, so the ball is in @samreid's court to figure this out.

**Comment by samreid** [comment] 2016-03-28 21:24
@jessegreenberg recently reported fixing memory problems by using image instead of mipmap, we could investigate this as well.

**Comment by samreid** [comment] 2016-03-28 22:16
rc.1 isn't crashing for me on iPad3 on iOS 9.2.1.

**Comment by samreid** [comment] 2016-03-28 22:18
I built a version with 9 screens instead of 3, and received a "A problem occurred with this webpage so it was reloaded".  After this initial crash, the 9 screen sim loads and runs until I tap enough screens, then it crashed.

**Comment by samreid** [comment] 2016-03-28 22:23
I built a version with 6 screens, and it crashed during load, then came up OK.  Then crashed again after I tapped through all 6 screens.

**Comment by samreid** [comment] 2016-03-28 22:25
All images in the app are already image, not mipmap, so that won't be a possible avenue for investigation.

**Comment by samreid** [comment] 2016-03-28 22:34
Measuring heap size (MB) as a function of number of screens:

1: 22.8
2: 29.9
3: 35.4
4: 42.4

![image](https://cloud.githubusercontent.com/assets/679486/14092222/ab456c28-f502-11e5-8000-dfb8ac337c1b.png)

**Comment by samreid** [comment] 2016-03-29 02:24
Chrome says most of the memory is in DOM elements:

![image](https://cloud.githubusercontent.com/assets/679486/14096070/19eb5c12-f523-11e5-8d36-48335cc2c3fc.png)

**Comment by samreid** [comment] 2016-03-29 16:18
@jonathanolson said it may be good to collaborate on this, could try canvas.

**Comment by samreid** [comment] 2016-03-29 19:19
@jonathanolson and I worked on this, we changed the max dimension of the SpriteSheet from 2048x2848 to 1024x1024 and this allowed us to run 6 screens on iPad3 without crashing (normally crashed at 5th screen).  So we added code in Image.js to disallow WebGL for images that don't fit on the sprite sheet.  I'm running simulation tests with test-server on to see if any new problems arise from these scenery changes.  If it seems clean, I'll commit.

I checked in `neuron` to see if there are any images larger than 1024x1024 and it doesn't appear to have any images as all.

**Comment by samreid** [comment] 2016-03-29 21:06
Now that https://github.com/phetsims/scenery/issues/539 has been addressed, let's publish a version for dev testing on the iPad2.

**Comment by samreid** [comment] 2016-03-29 21:14
I published dev.3 for testing.  I noted that its JS Heap is unchanged at 35.5MB, but it should be tested on the iPad2 where it crashed previously:

http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.0-dev.3/energy-skate-park-basics_en.html

@elisemorgan or @phet-steele can you test this on the device where it crashed earlier?

**Comment by samreid** [comment] 2016-03-29 21:18
I'll leave this assigned to myself and on hold while testing proceeds in tasks.

**Comment by samreid** [comment] 2016-03-30 12:46
Confirmed in the tasks issue, closing.

**Closed by samreid** 2016-03-30 12:46 UTC
Labels: priority:2-high, status:on-hold, type:bug
