### ISSUE TITLE
Skater falls through track when dropped from various heights when x = 4.5 to 5 m on quarter pipe ramp option

### ISSUE THREAD

**Issue by maggiewiseman** [phetsims/energy-skate-park-basics#369] opened 2017-04-22 13:19 UTC
Test device: Mac Airbook

Operating System: Sierra 10.12.4

Browser: Chrome Version 57.0.2987.133 (64-bit)

Problem description:
Skater falls through track when dropped precisely from position (5,3) on graph (3 meters up, 5 boxes to the right from the origin.  If skater is dropped at (5, 2) or (5, 4) she follows the ramp as expected.  Generally, the sim is just inconsistent around x = 4.5 to 5 m.  At certain heights she falls through the track and at other heights above and below a given point she will follow the track. 

I also tested in the live version and it has the same bug. 

Steps to reproduce:

1. open sim, click on intro option
2. show grid (can reproduce w/o grid, but it is much easier to find the right spot with the grid)
3. click on quarter pipe ramp option
4. drag skater so that red dot at bottom of skateboard is at coordinate (5,3), (5,5), (5,7), (4.5, 10) or (5,11) on the grid and drop her. She will appear in front of the track as shown in screenshot below instead of following track. 

Screenshots:
![screen shot 2017-04-22 at 8 49 24 am](https://cloud.githubusercontent.com/assets/17385784/25304618/0e2e8c20-2739-11e7-9bb2-7951d18704b1.png)

Related to:
phetsims/tasks#751

Troubleshooting information (do not edit):
Name: ‪Energy Skate Park: Basics‬
URL: https://phet.colorado.edu/sims/html/energy-skate-park-basics/latest/energy-skate-park-basics_en.html
Version: 1.1.5 2017-04-16 06:50:05 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Language: en-US
Window: 1317x1041
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"084c71cf","branch":"HEAD"},"babel":{"sha":"02e6456f","branch":"master"},"brand":{"sha":"ae19edf4","branch":"HEAD"},"chipper":{"sha":"97148ee1","branch":"HEAD"},"dot":{"sha":"33ae235e","branch":"HEAD"},"energy-skate-park-basics":{"sha":"7dcd05e5","branch":"HEAD"},"joist":{"sha":"2f8a4836","branch":"HEAD"},"kite":{"sha":"24ad131a","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"64051904","branch":"HEAD"},"scenery":{"sha":"4c1b5315","branch":"HEAD"},"scenery-phet":{"sha":"71c5dea5","branch":"HEAD"},"sherpa":{"sha":"2b2bdfd9","branch":"HEAD"},"sun":{"sha":"953074cc","branch":"HEAD"},"tandem":{"sha":"2441eec6","branch":"HEAD"}}

**Comment by samreid** [comment] 2017-04-23 00:16
I reproduced the problem, @ariel-phet can you prioritize?

**Comment by ariel-phet** [comment] 2017-04-24 22:06
Nice catch @maggiewiseman!

Since this bug exists in the published version (but does not seem to have caused major issues), I am going to mark priority deferred until we revisit this sim (likely when we make the full version)

**Comment by megan-phet** [comment] 2018-07-13 19:01
I also found this problem on my macOS 10.13.5 + all browsers. It seems like the skater will fall through the track whenever she is dropped on the portion of the track that is in close proximity to the ground. This occurred in the Intro, Friction, and Playground screen.

Noticed while doing testing for phetsims/QA/issues/134.

[video](https://drive.google.com/open?id=1iDAgePIRhzUBCXkmLHhAQata97E6YBhM)

**Comment by samreid** [comment] 2018-07-17 15:15
Perhaps if the skater crosses both the ground and the track in the same time step, the code currently doesn't check which the skater crossed *first*.

**Comment by KatieWoe** [comment] 2018-07-18 15:43
Good catch.  I was also able to replicate this on different tracks and some different heights.  This can also be done on the curved track if you drop the skater just to the left of the x=2 coordinate.  Most y values worked for this.
![drop track](https://user-images.githubusercontent.com/41024075/42892424-0a06188a-8a6f-11e8-93c1-dd80bc729703.gif)

**Comment by KatieWoe** [comment] 2018-07-18 16:17
One more example with the bowl-shaped track.
Test device: Dell Laptop

Operating System: Windows 10

Browser: Chrome Version 67.0.3396.99

![track drop two](https://user-images.githubusercontent.com/41024075/42894298-b54cf6c4-8a73-11e8-8bbc-4d37748b6962.gif)

**Comment by jessegreenberg** [comment] 2019-12-19 16:48
This is a duplicate of https://github.com/phetsims/energy-skate-park/issues/159, closing this issue. https://github.com/phetsims/energy-skate-park-basics/issues/369#issuecomment-405619490 was also suggested there.

**Closed by jessegreenberg** 2019-12-19 16:48 UTC
Labels: priority:5-deferred, type:bug
