### ISSUE TITLE
Skater can fall outside of loop and skater can fall through track

### ISSUE THREAD

**Issue by megan-phet** [phetsims/energy-skate-park-basics#421] opened 2018-07-10 23:02 UTC
**Test device:**
- MacBook Pro

**Operating System:**
- macOS 10.13.5

**Browser:**
- All latest

phetsims/QA/issues/134 Are these acceptable behaviors?

- [Skater falls outside of loop](https://drive.google.com/open?id=1N0NlRvqYULcLoxCuOPW5xb8rZm6dWOW4)
- [Skater falls through track](https://drive.google.com/open?id=1FqS6lNk8VcYjdsTcIfmeRCSKk04cgGd6)

**Comment by jessegreenberg** [comment] 2018-07-16 15:39
Stepping through `EnergySkateParkBasicsModel.interactWithTracksWhileFalling`, it looks like `this.crossedTrack` is returning false in these cases.

**Comment by jessegreenberg** [comment] 2018-07-16 15:54
Time consuming to iterate/create test tracks but I just found debugTrack query parameter will be really helpful. @ariel-phet can you please review this issue and prioritize, should it be fixed for the phetio/LoL release?

**Comment by jessegreenberg** [comment] 2018-09-24 18:43
The first video is a duplicate of #434. The second video looks like something different.

**Comment by ariel-phet** [comment] 2018-09-27 06:02
@jessegreenberg the second video is interesting...since there is presumably no friction (which is what the sim state appears to be set to) it seems like the skater should go around indefinitely. This seems like a pretty clever case to set up, and I am a bit surprised the behavior changes...maybe some sensitive dependence on conditions and floating point error type thing?

Anyhow, the second video warrants investigation, but I would put it at low priority. Would be nice to figure out what is going on, but no necessarily crucial since this sim has been out in the world for quite awhile without any complaints about the physics.

**Comment by jessegreenberg** [comment] 2019-12-19 17:18
> The first video is a duplicate of #434.

And #434 was closed because this type of track is not pedagogically useful.

Ill make a new issue for the "Skater falls out of loop" problem in energy-skate-park.

**Closed by jessegreenberg** 2019-12-19 17:18 UTC
Labels: priority:4-low, type:bug
