### ISSUE TITLE
CT Assertion Failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#443] opened 2018-11-20 16:16 UTC
```
energy-skate-park-basics : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/assert/js/assert.js:22:13)
    at SkaterState.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/SkaterState.js?bust=1542715827960:270:17)
    at EnergySkateParkBasicsModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542715827960:496:26)
    at EnergySkateParkBasicsModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542715827960:517:21)
    at EnergySkateParkBasicsModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542715827960:985:21)
    at EnergySkateParkBasicsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542715827960:1296:39)
    at EnergySkateParkBasicsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542715827960:402:31)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/joist/js/Sim.js?bust=1542715827960:205:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/axon/js/Emitter.js?bust=1542715827960:194:53)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1542711601136/joist/js/Sim.js?bust=1542715827960:907:34)
id: Bayes Chrome
Approximately 11/20/2018, 4:00:01 AM
energy-skate-park-basics : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 11/20/2018, 4:00:01 AM
energy-skate-park-basics : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 11/20/2018, 4:00:01 AM
```

**Comment by samreid** [comment] 2018-12-07 15:36
On hold until https://github.com/phetsims/energy-skate-park/issues/6 is complete

**Comment by samreid** [comment] 2018-12-09 15:49
Duplicate of https://github.com/phetsims/energy-skate-park/issues/45, closing.

**Closed by samreid** 2018-12-09 15:49 UTC
Labels: type:automated-testing
