### ISSUE TITLE
Sharp vertex in tracks makes skater spaz and makes total energy increase

### ISSUE THREAD

**Issue by megan-phet** [phetsims/energy-skate-park-basics#418] opened 2018-07-10 20:06 UTC
**Test device:**
- MacBook Pro

**Operating System:**
- macOS 10.13.5

**Browser:**

- All Latest

**Problem description:**

For phetsims/QA/issues/134. When the skater is stopped on a sharp vertex of the track, she moves up and down the track rapidly, and she can somehow obtain more kinetic energy. The pie chart gets much larger, and the kinetic energy and total energy on the bar chart increase. See video. 

Related: 
phetsims/energy-skate-park-basics/issues/193
phetsims/energy-skate-park-basics/issues/177

**Steps to reproduce:**
1. make a sharp vertex with the track
    - connect two tracks
    - drag the middle down
    - drag the two sides together
  (this might take a few tries)
2. put the skater on the track
3. wait (to speed up process increase the friction to maximum)

**Screenshots:**
- [Track](https://drive.google.com/open?id=1wXofrvLHwhUKifOh-OxgFy8bmOCJO8aq)
- [Video](https://drive.google.com/open?id=1G5gQJKfA_qjRwTK2ytSoV3n_74GrLv8e)

**Troubleshooting information (do not edit):**
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.1 Safari/605.1.15
Language: en-US
Window: 1310x736
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 NVIDIA-10.30.33 355.11.10.10.35.101)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by KatieWoe** [comment] 2018-07-10 20:11
I have a theory about what may cause the sharp track vertex.  When a sharp vertex in the track is made one of the points in the track shifts randomly.  Usually this creates a more gentle curve.  However, if the point chosen moves in a direction that still results in a sharp vertex the points do not shift again to correct it.

**Comment by samreid** [comment] 2018-07-15 23:28
Assigned to @ariel-phet for review, prioritization and timeline.

**Comment by jessegreenberg** [comment] 2018-07-16 18:50
I will wait to look into it until hearing about https://github.com/phetsims/energy-skate-park-basics/issues/418#issuecomment-405126328.

**Comment by KatieWoe** [comment] 2018-07-18 16:01
An easier way to reproduce this.
1. Drop the skater on  a track with a gentle vertex.
2. While the skater is moving, drag one of the track points so that a sharp vertex on the track
3. Fire on hold.  The vertex will remain as long as you do not let go of the point.  Once you let go the vertex will likely correct itself.

Screenshot
![vertex](https://user-images.githubusercontent.com/41024075/42893430-8588d9e6-8a71-11e8-8dee-3f832c6f634e.gif)

**Comment by megan-phet** [comment] 2018-07-26 19:08
It looks like it's fixed.

**Comment by jessegreenberg** [comment] 2018-07-26 19:14
@megan-phet did you mean to close this issue? I don't believe anything has been done to fix this issue.

**Comment by megan-phet** [comment] 2018-07-31 17:51
Sorry @jessegreenberg didn't mean to close it, it's still an issue.

**Comment by ariel-phet** [comment] 2018-09-27 05:40
@KatieWoe @jessegreenberg I think this is an "acceptable edge case" we should not do anything about, since you need to deliberately hold the drag point and keep it active for the track to not smooth itself out. The super kinked track is not pedagogically useful, so I don't think we need to do anything about this case.

Letting either of you close this issue.

**Comment by KatieWoe** [comment] 2018-09-27 14:39
@ariel-phet @jessegreenberg One concern I have before we close.  While it is easier to make the sharp vertex by holding the track there, it can sometimes be there after letting go.  Having trouble finding the issue at the moment, but when the track moves to get rid of the sharp point, the second position may also have a sharp point.  If this happens, the track is not repositioned a second time and the sharp point remains.

**Comment by ariel-phet** [comment] 2018-10-03 01:58
@KatieWoe sharp kinks are generally desirable to avoid, agreed, as they cause odd behavior. Perhaps find reproducible steps to what you describe above, make a separate issue, and close this one.

**Closed** 2018-10-03 14:58 UTC
Labels: type:bug

**Comment by KatieWoe** [comment] 2020-02-05 23:44
Seen in https://github.com/phetsims/QA/issues/470 along with https://github.com/phetsims/energy-skate-park-basics/issues/440
