### ISSUE TITLE
Bars in bar graph appear in front of track

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#425] opened 2018-07-12 15:35 UTC
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome and Edge
**Problem description:**
If tracks in the playground screen are laid over the energy bar graph they will appear in front of the axes, titles, and labels.  However, it will appear behind the bars showing energy.  The skater herself will appear in front of he bars showing energy.  This is for phetsims/QA/issues/134
**Steps to reproduce:**
1. Go to the playground screen
2. Select the bar graph checkbox
3. Build a track that is in front of the graph (Easiest to see if built towards the bottom of the graph, so the bars don't need to be tall to reach it)
4. Start the skater down the track

**Screenshots:**
![bar over track](https://user-images.githubusercontent.com/41024075/42643476-7423d1fc-85b6-11e8-842e-63c02f1c4137.PNG)
![bar over track b](https://user-images.githubusercontent.com/41024075/42643489-7936a458-85b6-11e8-863c-c98e15280378.PNG)

Troubleshooting information (do not edit):
<details>
Name: ‪Energy Skate Park: Basics‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html
Version: 1.4.0-dev.1 2018-06-20 00:09:06 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1536x741
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"f0522e7c","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"e8946524","branch":"master"},"dot":{"sha":"6482f8c9","branch":"master"},"energy-skate-park-basics":{"sha":"288fcefd","branch":"master"},"joist":{"sha":"22e437d5","branch":"master"},"kite":{"sha":"a1086efc","branch":"master"},"phet-core":{"sha":"17326041","branch":"master"},"phet-io":{"sha":"3ea0727a","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"53708616","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"8a546a32","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"1527afd6","branch":"master"},"phet-io-wrappers":{"sha":"8d814eab","branch":"master"},"phetcommon":{"sha":"6ec8cd89","branch":"master"},"query-string-machine":{"sha":"4182612f","branch":"master"},"scenery":{"sha":"88cb642e","branch":"master"},"scenery-phet":{"sha":"7bcde0b2","branch":"master"},"sherpa":{"sha":"88c3b828","branch":"master"},"sun":{"sha":"7579e8fa","branch":"master"},"tandem":{"sha":"8461b6f3","branch":"master"}}
</details>

**Comment by jessegreenberg** [comment] 2018-07-13 19:21
Thanks @KatieWoe, fixed with the above commit:
![capture](https://user-images.githubusercontent.com/6396244/42710022-a39b5222-869f-11e8-875f-cea8d973641f.PNG)

**Comment by jessegreenberg** [comment] 2018-07-13 19:38
Reopening, @phet-steele mentioned this layering was intentional because of https://github.com/phetsims/energy-skate-park-basics/issues/295.

**Comment by jessegreenberg** [comment] 2018-07-13 19:39
Lets pick this up in #295 since this issue is a duplicate of that one.

**Closed by jessegreenberg** 2018-07-13 19:39 UTC
Labels: type:bug

**Comment by jessegreenberg** [comment] 2019-05-23 17:13
This is no longer true since WebGL is being removed in https://github.com/phetsims/energy-skate-park/issues/66 and we no longer need the layering to support that.
